<td width="5%"></td>
</tr>
<tr>
<td width=20% align=left valign=top>
<a href="orderform.php">  Первая лабораторная работа </a>
<br><br>

<a href="orderform_2.php">  Вторая лабораторная работа </a>
<br><br>

<a href="orderform_3.php">  Третья лабораторная работа </a>
<br><br>

<a href="orderform_4.php">  Четвертая лабораторная работа </a>
<br><br>

<a href="index_5.php">  Пятая лабораторная работа </a>
<br><br>

<a href="index_6.php">  Шестая лабораторная работа </a>
</td>

</td>
<td>   </td>
</tr>

</table>
<table border=1 width=100% height=10%>
<td width=100% height=10% align=center> Кемеровский институт (филиал) РГТЭУ, Кафедра вычислительной техники и информационных технологий, 2020 </td>
</table>
</body>
</html>

