<html>
<head>

 <title>РГТЭУ Кемеровский институт</title>
 <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
 <META name="Author" content="http://ailus.ru"><meta name="Copyright" content="http://ailus.ru">

</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" rightmargin="0" bottommargin="0" bgcolor="#ffffff">
<link href="style.css" type="text/css" rel="STYLESHEET">


<table border=1 width=100% height=20%>
<tr>
<td width=100% height=20% align=center> Лабораторные работы по курсу "Разработка интернет приложений в сфере коммерциии посредством PHP и MySQL" <br> Студента группы ПИс-171: Гагарин Илья Николаевич <br> Проверил: Маринова С.А. </td>
</table>


<table border=1 width=100% >
<tr>
<td align="center"><b>Меню</b></td>
<td width=75%  align=center  rowspan="2">
